/* Advent of code 2018
** day 5
*/
DEFINE VARIABLE s AS LONGCHAR NO-UNDO.
DEFINE VARIABLE i AS INTEGER  NO-UNDO.
PAUSE 0 BEFORE-HIDE. 

DEFINE TEMP-TABLE tt
  FIELD c AS CHARACTER
  FIELD i AS INTEGER.

COPY-LOB FILE "2018-05.dat" TO s.

DO i = 0 TO 25:
  CREATE tt.
  ASSIGN tt.c = CHR(65 + i).
  RUN react(s,tt.c,OUTPUT tt.i).
END.

FOR EACH tt BY tt.i:
  MESSAGE tt.c tt.i VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
  LEAVE.
END.

PROCEDURE react:
  DEFINE INPUT  PARAMETER s AS LONGCHAR  NO-UNDO.
  DEFINE INPUT  PARAMETER c AS CHARACTER NO-UNDO.
  DEFINE OUTPUT PARAMETER j AS INTEGER   NO-UNDO. 

  DEFINE VARIABLE a AS CHARACTER NO-UNDO CASE-SENSITIVE.
  DEFINE VARIABLE b AS CHARACTER NO-UNDO CASE-SENSITIVE.
  DEFINE VARIABLE i AS INTEGER   NO-UNDO.
  
  s = REPLACE(s,c,'').

  REPEAT:
    j = LENGTH(s).
  
    #loop:
    DO i = 1 TO LENGTH(s) - 1:
  
      IF ETIME > 1000 THEN
      DO:
        MESSAGE c LENGTH(s).
        ETIME(YES).
      END.                
  
      a = SUBSTRING(s,i,1).
      b = SUBSTRING(s,i + 1,1).
      IF a <> b AND CAPS(a) = CAPS(b) THEN OVERLAY(s,i,2) = '..'.
    END.
    s = REPLACE(s,'.','').
  
    IF LENGTH(s) = j THEN RETURN. 
  END. 
END PROCEDURE. 