/* AoC 2020 day 5a + b
*/
DEFINE VARIABLE cLine  AS CHARACTER NO-UNDO.
DEFINE VARIABLE iMax   AS INTEGER   NO-UNDO.
DEFINE VARIABLE lSeat  AS LOGICAL   NO-UNDO EXTENT 1024.
DEFINE VARIABLE i      AS INTEGER   NO-UNDO.
DEFINE VARIABLE iValue AS INTEGER   NO-UNDO.

INPUT FROM day-05.dat.
REPEAT:
  IMPORT cLine.
  cLine  = REPLACE(REPLACE(REPLACE(REPLACE(cLine,'F','0'),'B','1'),'R','1'),'L','0').
  iValue = System.Convert:ToInt32(cLine,2).
  iMax   = MAXIMUM(iMax,iValue).
  lSeat[iValue] = TRUE.
END.
INPUT CLOSE.

MESSAGE 'Part 1:' iMax VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.

DO i = 2 TO 1023:
  IF NOT lSeat[i] AND lSeat[i - 1] AND lSeat[i + 1] THEN 
    MESSAGE 'Part 2:' i VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
END.
