/* Advent of code 
 * 2016-2b
 */
DEFINE VARIABLE cInput AS CHARACTER   EXTENT 5 NO-UNDO.
DEFINE VARIABLE iLine  AS INTEGER     NO-UNDO.
DEFINE VARIABLE cPos   AS CHARACTER   NO-UNDO.
DEFINE VARIABLE cCode  AS CHARACTER   NO-UNDO.
DEFINE VARIABLE iChar  AS INTEGER     NO-UNDO.

/* Define keypad layout */
DEFINE TEMP-TABLE ttKeypad NO-UNDO
  FIELD cc AS CHARACTER
  FIELD xx AS INTEGER
  FIELD yy AS INTEGER
  .
DEFINE BUFFER currentPos FOR ttKeypad.

/* Fill keypad */
CREATE ttKeypad. ASSIGN ttKeypad.xx = 3 ttKeypad.yy = 1 ttKeypad.cc = '1'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 2 ttKeypad.yy = 2 ttKeypad.cc = '2'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 3 ttKeypad.yy = 2 ttKeypad.cc = '3'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 4 ttKeypad.yy = 2 ttKeypad.cc = '4'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 1 ttKeypad.yy = 3 ttKeypad.cc = '5'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 2 ttKeypad.yy = 3 ttKeypad.cc = '6'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 3 ttKeypad.yy = 3 ttKeypad.cc = '7'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 4 ttKeypad.yy = 3 ttKeypad.cc = '8'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 5 ttKeypad.yy = 3 ttKeypad.cc = '9'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 2 ttKeypad.yy = 4 ttKeypad.cc = 'A'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 3 ttKeypad.yy = 4 ttKeypad.cc = 'B'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 4 ttKeypad.yy = 4 ttKeypad.cc = 'C'.
CREATE ttKeypad. ASSIGN ttKeypad.xx = 3 ttKeypad.yy = 5 ttKeypad.cc = 'D'.

cInput[1] = "UUURRRRULRDLRDRRDURDDDLLDLLLULDUDDLDLULUURULRLDLRRLLLRRDRRLDDLLULUDUDDLRDRDUURDLURUURLRULLDDURULRRURDUURLULUUUURDDDDUUDLULRULLLRLLRRRURDLLRLLRRRUURULRDRUUDDDDDLLLRURRURRUURDUURDDRDLULRRLLLDRRRLURRLLURLDRRDDLDLRRLLRDRLLLLDLULDLRRDRRLDDURLULLUDLUDRRDRRLRLULURDRLRLUUUDLRLDLLLURDUDULULDDRUUURLLLDLLDDUDDRURURUDDLUULRDRRRRLDRDDURLUDURDULLDLUDLULDRLRLLRLLLLRURDURLLDRRDRLRUUUUULLLRUDURUDLLLUDLLLLRDLDRDUDRURLUDDUDDURLUUUUDDLLUDLULLLLLDUDLLRLRRDDDULULRLDRLLULDLUDLLURULRDDUURULRDLDLDLRL".
cInput[2] = "URUUURDULUDLUUUUDDRRRDRRRLDUDLRDRRDRDDLRUULDLLDUDULLLRLDRDRRLDLDLUUDRUULDUDULDUDURURDDURULDLURULRLULDUDDUULDLLLDDURDDRDDURUULUUDRLDDULDRRRRDURRUDLLLURDDDLRULLRDDRDDDDLUUDRDUULRRRRURULDDDLDDRDRRUDRRURUDRDDLDRRRLLURURUULUUDRDULLDRLRDRRDDURDUDLDRLUDRURDURURULDUUURDUULRRRRRUDLLULDDDRLULDDULUDRRRDDRUDRRDLDLRUULLLLRRDRRLUDRUULRDUDRDRRRDDRLLRUUDRLLLUDUDLULUUDULDRRRRDDRURULDULLURDLLLDUUDLLUDRLDURRRLDDDURUDUDURRULDD".
cInput[3] = "LRUDDULLLULRLUDUDUDRLLUUUULLUDLUUUUDULLUURDLLRDUDLRUDRUDDURURRURUDLLLRLDLUDRRRRRRDLUURLRDDDULRRUDRULRDRDDUULRDDLDULDRRRDDLURRURLLLRURDULLRUUUDDUDUURLRLDDUURLRDRRLURLDRLLUUURDRUUDUUUDRLURUUUDLDRRLRLLRRUURULLLRLLDLLLDULDDLDULDLDDRUDURDDURDUDURDLLLRRDDLULLLUDURLUDDLDLUUDRDRUDUUDLLDDLLLLDRDULRDLDULLRUDDUULDUDLDDDRUURLDRRLURRDDRUUDRUDLLDLULLULUDUDURDDRLRDLRLDRLDDRULLLRUDULDRLRLRULLRLLRRRLLRRRDDRULRUURRLLLRULDLUDRRDDLLLUDDUDDDLURLUDRDLURUUDLLDLULURRLLDURUDDDDRLULRDDLRLDDLRLLDDRRLRDUDUUULRRLRULUDURDUDRLRLRUDUDLLRRRRLRRUDUL".
cInput[4] = "RULLLLUUUDLLDLLRULLRURRULDDRDLUULDRLLRUDLLRRLRDURLLDUUUUURUUURDLUURRLDDDLRRRRLRULDUDDLURDRRUUDLRRRDLDDUDUDDRUDURURLDULLDLULDLLUDLULRDRLLURRLLDURLDLRDLULUDDULDLDDDDDUURRDRURLDLDULLURDLLDDLLUDLDLDRLRLDLRDRLDLRRUUDRURLUUUDLURUULDUDRDULLDURUDLUUURRRLLDUDUDDUUULLLRUULDLURUDDRLUDRDDLDLLUDUDRRRDDUUULUULLLRLLUURDUUDRUUULULLDLDRUUDURLLUULRLDLUURLLUUDRURDDRLURULDUDUUDRRUUURDULRLDUUDDRURURDRRULDDDRLUDLLUUDURRRLDLRLRDRURLURLLLRLDDLRRLDLDDURDUUDRDRRLDRLULDRLURUUUDDRLLLDDLDURLLLLDRDLDRRUDULURRLULRDRLLUULLRLRDRLLULUURRUDRUDDDLLDURURLURRRDLLDRDLUDRULULULRLDLRRRUUDLULDURLRDRLULRUUURRDDLRUURUDRURUDURURDD".
cInput[5] = "DURRDLLLDDLLDLLRLULULLRDLDRRDDRDLRULURRDUUDDRLLDDLDRRLRDUDRULDLRURDUUDRDDLLDRRDRUDUDULLDDDDLDRRRLRLRDRDLURRDDLDDDUUDRDRLLLDLUDDDLUULRDRLLLRLLUULUDDDRLDUUUURULRDDURRDRLUURLUDRLRLLLDDLRDDUULRRRRURDLDDDRLDLDRRLLDRDDUDDUURDLDUUDRDLDLDDULULUDDLRDDRLRLDDLUDLLDRLUDUDDRULLRLDLLRULRUURDDRDRDRURDRRLRDLLUDDRRDRRLDDULLLDLUDRRUDLDULDRURRDURLURRLDLRDLRUDLULUDDRULRLLDUURULURULURRLURRUULRULRRRLRDLULRLRLUDURDDRUUURDRLLRRRDDLDRRRULLDLRDRULDRRLRRDLUDDRDDDUUURRLULLDRRUULULLRRRRLDDRDDLUURLLUDLLDUDLULUULUDLLUUURRRUDDDRLLLRDRUUDUUURDRULURRLRDLLUURLRDURULDRRUDURRDDLDRLDRUUDRLLUDLRRU".

/* /* Test, should get code 5DB3 */ */
/* cInput[1] = "ULL".               */
/* cInput[2] = "RRDDD".             */
/* cInput[3] = "LURDL".             */
/* cInput[4] = "UUUUD".             */
/* cInput[5] = "".                  */

cPos = '5'.

DO iLine = 1 TO 5:
  DO iChar = 1 TO LENGTH(cInput[iLine]):

    FIND currentPos WHERE currentPos.cc = cPos.

    CASE SUBSTRING(cInput[iLine],iChar,1):
      WHEN 'U' THEN FIND ttKeypad WHERE ttKeypad.xx = currentPos.xx AND ttKeypad.yy = currentPos.yy - 1 NO-ERROR.
      WHEN 'D' THEN FIND ttKeypad WHERE ttKeypad.xx = currentPos.xx AND ttKeypad.yy = currentPos.yy + 1 NO-ERROR.
      WHEN 'L' THEN FIND ttKeypad WHERE ttKeypad.xx = currentPos.xx - 1 AND ttKeypad.yy = currentPos.yy NO-ERROR.
      WHEN 'R' THEN FIND ttKeypad WHERE ttKeypad.xx = currentPos.xx + 1 AND ttKeypad.yy = currentPos.yy NO-ERROR.
    END CASE.

    IF AVAILABLE ttKeypad THEN cPos = ttKeypad.cc.
  END.

  cCode = SUBSTITUTE('&1&2',cCode,cPos).
END.

MESSAGE cCode
  VIEW-AS ALERT-BOX INFO BUTTONS OK.

/* ---------------------------                  */
/* Information (Press HELP to view stack trace) */
/* ---------------------------                  */
/* AC8C8                                        */
/* ---------------------------                  */
/* OK   Help                                    */
/* ---------------------------                  */

