/* AoC 2015 day 04 a + b
 */ 
DEFINE VARIABLE i AS INTEGER NO-UNDO.

/* part 1 */
REPEAT:
  i = i + 1.

  IF STRING(HEX-ENCODE(MD5-DIGEST('yzbqklnj' + STRING(i)))) BEGINS "00000" THEN 
  DO:
    MESSAGE i VIEW-AS ALERT-BOX INFORMATION BUTTONS OK. /* 282749 */
    LEAVE.
  END.
  
  IF ETIME > 1000 THEN DO: MESSAGE i. ETIME(YES). END. PROCESS EVENTS. 
END.

/* part 2 */
REPEAT:
  i = i + 1.

  IF STRING(HEX-ENCODE(MD5-DIGEST('yzbqklnj' + STRING(i)))) BEGINS "000000" THEN 
  DO:
    MESSAGE i VIEW-AS ALERT-BOX INFORMATION BUTTONS OK. /* 9962624 */
    LEAVE.
  END.
  
  IF ETIME > 1000 THEN DO: MESSAGE i. ETIME(YES). END. PROCESS EVENTS. 
END.

