/* AoC 2023 day 06b
 */ 
DEFINE VARIABLE iTime   AS INT64     NO-UNDO.
DEFINE VARIABLE iDist   AS INT64     NO-UNDO.
DEFINE VARIABLE cDummy  AS CHARACTER NO-UNDO.
DEFINE VARIABLE i       AS INT64     NO-UNDO.
DEFINE VARIABLE j       AS INT64     NO-UNDO.
DEFINE VARIABLE iWins   AS INT64     NO-UNDO.
DEFINE VARIABLE iAnswer AS INT64     NO-UNDO.

INPUT FROM "data.txt".
IMPORT UNFORMATTED cDummy. iTime = INT64(REPLACE(ENTRY(2,cDummy,":")," ","")).
IMPORT UNFORMATTED cDummy. iDist = INT64(REPLACE(ENTRY(2,cDummy,":")," ","")).
INPUT CLOSE. 

DO j = 1 TO iTime:
  IF (j * iTime - EXP(j,2)) > iDist THEN iWins = iWins + 1.
  IF ETIME > 1000 THEN 
  DO:
    MESSAGE j '/' iTime ' |' iWins. ETIME(YES). PROCESS EVENTS. 
  END.
END.

MESSAGE iWins
  VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.


