/* AoC 2023 day 06a 
 */ 
DEFINE VARIABLE cTime   AS CHARACTER NO-UNDO INITIAL " 54,  94,  65,  92".
DEFINE VARIABLE cDist   AS CHARACTER NO-UNDO INITIAL "302,1476,1029,1404".
DEFINE VARIABLE iTime   AS INT64 NO-UNDO.
DEFINE VARIABLE iDist   AS INT64 NO-UNDO.
DEFINE VARIABLE i       AS INT64 NO-UNDO.
DEFINE VARIABLE j       AS INT64 NO-UNDO.
DEFINE VARIABLE iWins   AS INT64 NO-UNDO.
DEFINE VARIABLE iAnswer AS INT64 NO-UNDO INITIAL 1.

DO i = 1 TO NUM-ENTRIES(cTime):
  iTime = INTEGER(ENTRY(i,cTime)).
  iDist = INTEGER(ENTRY(i,cDist)).
  iWins = 0.
  DO j = 1 TO iTime:
    IF (j * iTime - EXP(j,2)) > iDist THEN iWins = iWins + 1.
  END.
  iAnswer = iAnswer * iWins.
END.

MESSAGE iAnswer
  VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.

