/* Advent of code 2018
** day 5 
*/
DEFINE VARIABLE s AS LONGCHAR  NO-UNDO.
DEFINE VARIABLE a AS CHARACTER NO-UNDO CASE-SENSITIVE.
DEFINE VARIABLE b AS CHARACTER NO-UNDO CASE-SENSITIVE.
DEFINE VARIABLE i AS INTEGER   NO-UNDO.
DEFINE VARIABLE X AS INTEGER   NO-UNDO.

COPY-LOB FILE "2018-05.dat" TO s.
PAUSE 0 BEFORE-HIDE. 

REPEAT:
  X = LENGTH(s).

  #loop:
  DO i = 1 TO LENGTH(s) - 1:
    a = SUBSTRING(s,i,1).
    b = SUBSTRING(s,i + 1,1).
    IF a <> b AND CAPS(a) = CAPS(b) THEN OVERLAY(s,i,2) = '..'.
  END.
  s = REPLACE(s,'.','').

  IF LENGTH(s) = X THEN
  DO:
    MESSAGE X VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    LEAVE.
  END.
END. 

/* look at 2018-05a-stack.p for a faster solution */
