DEFINE VARIABLE cSeat  AS CHARACTER NO-UNDO EXTENT 10000.
DEFINE VARIABLE iScore AS INTEGER   NO-UNDO EXTENT 10000.
DEFINE VARIABLE i      AS INTEGER   NO-UNDO.
DEFINE VARIABLE cLine  AS CHARACTER NO-UNDO.
DEFINE VARIABLE iRow   AS INTEGER   NO-UNDO.
DEFINE VARIABLE iCol   AS INTEGER   NO-UNDO.

&GLOBAL-DEFINE rows 10
&GLOBAL-DEFINE cols 10

INPUT FROM "test.txt".
REPEAT:
  IMPORT cLine.
  iRow = iRow + 1.
  DO iCol = 1 TO LENGTH(cLine):
    i = (iRow - 1) * {&cols} + iCol.
    cSeat[i] = SUBSTRING(cLine,iCol,1).
  END.
END.
INPUT CLOSE. 

FUNCTION s RETURNS CHARACTER (X AS INTEGER, Y AS INTEGER):
  IF X < 1 OR X > {&cols} OR Y < 1 OR Y > {&rows} THEN RETURN ''.
  RETURN cSeat[(Y - 1) * {&cols} + X].
END FUNCTION.

FUNCTION p RETURNS INTEGER (X AS INTEGER, Y AS INTEGER):
  RETURN (Y - 1) * {&cols} + X.
END FUNCTION.

DO Y = 1 TO {&rows}:
  DO X = 1 TO {&cols}:
    i = 
  iScore[i] = INTEGER(
END.

MESSAGE s(3,1)
  VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.

