/* Advent of code 2018
** day 1
*/
DEFINE VARIABLE iFreq AS INTEGER   NO-UNDO.
DEFINE VARIABLE cLine AS CHARACTER NO-UNDO.

INPUT FROM "2018-01.dat".
REPEAT:
  IMPORT cLine.
  iFreq = iFreq + INTEGER(cLine).
END.
INPUT CLOSE. 

MESSAGE iFreq VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
